# Generated by Django 2.2.16 on 2020-10-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_form_index_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormSubmission',
        ),
    ]
